'use strict';

/**
 * CC Commander — Session Replay
 * Generates beautiful session summaries with stats, timelines, and shareable reports.
 * The killer feature: every CCC session gets a replay you can share, post to Linear, or review.
 */

var fs = require('fs');
var path = require('path');
var os = require('os');
var state = require('./state');

var REPLAY_DIR = path.join(os.homedir(), '.claude', 'commander', 'replays');

/**
 * Generate a session replay report
 */
function generateReplay(session) {
  if (!session) return null;

  var duration = session.duration ? formatDuration(session.duration) : 'unknown';
  var cost = session.cost ? '$' + session.cost.toFixed(2) : '$0.00';
  var filesCount = (session.filesChanged && session.filesChanged.length) || 0;
  var skillsUsed = (session.skillsUsed && session.skillsUsed.length) || 0;

  var report = '';
  report += '# Session Replay\n\n';
  report += '**' + (session.task || 'Untitled Session') + '**\n\n';

  // Stats bar
  report += '| Metric | Value |\n|--------|-------|\n';
  report += '| Duration | ' + duration + ' |\n';
  report += '| Cost | ' + cost + ' |\n';
  report += '| Files Changed | ' + filesCount + ' |\n';
  report += '| Skills Used | ' + skillsUsed + ' |\n';
  report += '| Status | ' + (session.outcome || 'completed') + ' |\n';
  if (session.linearIssueIdentifier) {
    report += '| Linear | ' + session.linearIssueIdentifier + ' |\n';
  }
  report += '\n';

  // Timeline
  report += '## Timeline\n\n';
  report += '- **Started:** ' + new Date(session.startTime).toLocaleString() + '\n';
  if (session.endTime) {
    report += '- **Ended:** ' + new Date(session.endTime).toLocaleString() + '\n';
  }
  report += '\n';

  // Files
  if (session.filesChanged && session.filesChanged.length > 0) {
    report += '## Files Changed (' + session.filesChanged.length + ')\n\n';
    session.filesChanged.forEach(function(f) {
      report += '- `' + f + '`\n';
    });
    report += '\n';
  }

  // Skills
  if (session.skillsUsed && session.skillsUsed.length > 0) {
    report += '## Skills Used\n\n';
    session.skillsUsed.forEach(function(s) {
      report += '- ' + s + '\n';
    });
    report += '\n';
  }

  // Score card
  report += '## Score Card\n\n';
  var score = calculateScore(session);
  report += '**Session Score: ' + score.total + '/100**\n\n';
  report += '- Completion: ' + score.completion + '/30\n';
  report += '- Efficiency: ' + score.efficiency + '/25\n';
  report += '- Scope: ' + score.scope + '/25\n';
  report += '- Cost: ' + score.cost + '/20\n';
  report += '\n';

  // Footer
  report += '---\n\n';
  report += '*Generated by CC Commander v2.0.0 — Session Replay*\n';

  return { markdown: report, score: score, session: session };
}

/**
 * Calculate session score (0-100)
 */
function calculateScore(session) {
  var completion = session.outcome === 'success' ? 30 : session.outcome === 'error' ? 10 : 20;
  var efficiency = 25;
  if (session.duration) {
    if (session.duration < 300) efficiency = 25; // < 5 min = fast
    else if (session.duration < 1800) efficiency = 20; // < 30 min = good
    else if (session.duration < 3600) efficiency = 15; // < 1 hour = ok
    else efficiency = 10; // > 1 hour = long
  }
  var scope = Math.min(25, (session.filesChanged ? session.filesChanged.length : 0) * 3);
  var costScore = 20;
  if (session.cost) {
    if (session.cost < 0.50) costScore = 20;
    else if (session.cost < 2.00) costScore = 15;
    else if (session.cost < 5.00) costScore = 10;
    else costScore = 5;
  }
  return { total: completion + efficiency + scope + costScore, completion: completion, efficiency: efficiency, scope: scope, cost: costScore };
}

/**
 * Save replay to disk
 */
function saveReplay(replay) {
  if (!replay) return null;
  if (!fs.existsSync(REPLAY_DIR)) fs.mkdirSync(REPLAY_DIR, { recursive: true });
  var filename = 'replay-' + (replay.session.id || Date.now()) + '.md';
  var filepath = path.join(REPLAY_DIR, filename);
  fs.writeFileSync(filepath, replay.markdown);
  return filepath;
}

/**
 * List recent replays
 */
function listReplays(limit) {
  if (!fs.existsSync(REPLAY_DIR)) return [];
  var files = fs.readdirSync(REPLAY_DIR)
    .filter(function(f) { return f.endsWith('.md'); })
    .sort()
    .reverse()
    .slice(0, limit || 10);
  return files.map(function(f) {
    return { filename: f, path: path.join(REPLAY_DIR, f) };
  });
}

/**
 * Post replay to Linear as a comment
 */
async function postToLinear(replay) {
  if (!replay || !replay.session.linearIssueId) return false;
  try {
    var linear = require('./integrations/linear');
    return await linear.addComment(replay.session.linearIssueId, replay.markdown);
  } catch (_e) { return false; }
}

function formatDuration(seconds) {
  if (seconds < 60) return seconds + 's';
  if (seconds < 3600) return Math.floor(seconds / 60) + 'm ' + (seconds % 60) + 's';
  return Math.floor(seconds / 3600) + 'h ' + Math.floor((seconds % 3600) / 60) + 'm';
}

module.exports = {
  generateReplay: generateReplay,
  calculateScore: calculateScore,
  saveReplay: saveReplay,
  listReplays: listReplays,
  postToLinear: postToLinear,
  REPLAY_DIR: REPLAY_DIR,
};
