'use strict';

const path = require('path');
const { evaluate } = require('./rule-engine');

const DIMENSIONS = ['security', 'testing', 'devops', 'quality', 'docs', 'architecture'];

const MATURITY_LEVELS = [
  { level: 1, name: 'Initial', min: 0 },
  { level: 2, name: 'Managed', min: 30 },
  { level: 3, name: 'Defined', min: 55 },
  { level: 4, name: 'Measured', min: 75 },
  { level: 5, name: 'Optimizing', min: 90 },
];

function healthScore(signals, recs) {
  const scores = {};
  const counts = {};

  for (const dim of DIMENSIONS) {
    scores[dim] = 100;
    counts[dim] = 0;
  }

  for (const rec of recs) {
    if (scores[rec.category] !== undefined) {
      scores[rec.category] -= rec.score * 0.3;
      counts[rec.category]++;
    }
  }

  for (const dim of DIMENSIONS) {
    scores[dim] = Math.max(0, Math.round(scores[dim]));
  }

  const total = DIMENSIONS.reduce((sum, dim) => sum + scores[dim], 0);
  const overall = Math.round(total / DIMENSIONS.length);

  return { overall, dimensions: scores, issueCounts: counts };
}

function maturityLevel(score) {
  let result = MATURITY_LEVELS[0];
  for (const level of MATURITY_LEVELS) {
    if (score >= level.min) result = level;
  }
  return result;
}

function generateReport(projectDir) {
  let signalScanner;
  try {
    signalScanner = require('./signal-scanner');
  } catch {
    signalScanner = null;
  }

  const signals = signalScanner ? signalScanner.scan(projectDir) : buildFallbackSignals(projectDir);
  const recs = evaluate(signals);
  const health = healthScore(signals, recs);
  const maturity = maturityLevel(health.overall);

  const projectName = path.basename(projectDir);
  const timestamp = new Date().toISOString().split('T')[0];

  let md = `# X-Ray Report: ${projectName}\n\n`;
  md += `**Date:** ${timestamp}\n`;
  md += `**Health Score:** ${health.overall}/100\n`;
  md += `**Maturity Level:** ${maturity.level} -- ${maturity.name}\n\n`;

  md += `## Dimension Scores\n\n`;
  md += `| Dimension | Score | Issues |\n`;
  md += `|-----------|-------|--------|\n`;
  for (const dim of DIMENSIONS) {
    const bar = scoreBar(health.dimensions[dim]);
    md += `| ${dim} | ${bar} ${health.dimensions[dim]}/100 | ${health.issueCounts[dim]} |\n`;
  }
  md += '\n';

  if (recs.length > 0) {
    md += `## Recommendations\n\n`;
    for (const rec of recs) {
      const badge = rec.priority <= 2 ? 'HIGH' : rec.priority <= 3 ? 'MED' : 'LOW';
      md += `### [${badge}] ${rec.explanation}\n`;
      md += `- **Skill:** \`/${rec.skill}\`\n`;
      md += `- **Category:** ${rec.category}\n`;
      md += `- **Impact Score:** ${rec.score}\n\n`;
    }
  } else {
    md += `## No Issues Found\n\nProject looks healthy across all dimensions.\n\n`;
  }

  md += `---\n*Generated by CCC X-Ray v1.0*\n`;

  return {
    markdown: md,
    health,
    maturity,
    recommendations: recs,
    signals,
  };
}

function scoreBar(score) {
  const filled = Math.round(score / 10);
  const empty = 10 - filled;
  return '[' + '#'.repeat(filled) + '-'.repeat(empty) + ']';
}

function buildFallbackSignals(projectDir) {
  const fs = require('fs');

  const exists = (f) => fs.existsSync(path.join(projectDir, f));

  return {
    hasPackageJson: exists('package.json'),
    hasLockfile: exists('package-lock.json') || exists('pnpm-lock.yaml') || exists('yarn.lock'),
    hasSource: exists('src') || exists('lib') || exists('commander'),
    hasTests: exists('tests') || exists('__tests__') || exists('test'),
    hasE2E: exists('e2e') || exists('playwright.config.ts') || exists('cypress.config.ts'),
    hasCI: exists('.github/workflows') || exists('.circleci') || exists('.gitlab-ci.yml'),
    hasDockerfile: exists('Dockerfile') || exists('docker-compose.yml'),
    hasDeployConfig: exists('vercel.json') || exists('fly.toml') || exists('render.yaml'),
    hasLintConfig: exists('.eslintrc.json') || exists('.eslintrc.js') || exists('eslint.config.js'),
    hasTsConfig: exists('tsconfig.json'),
    hasFormatter: exists('.prettierrc') || exists('.prettierrc.json') || exists('biome.json'),
    hasReadme: exists('README.md'),
    hasClaudeMd: exists('CLAUDE.md'),
    hasChangelog: exists('CHANGELOG.md'),
    hasGit: exists('.git'),
    hasUI: exists('src/components') || exists('app') || exists('pages'),
    hasAPI: exists('src/routes') || exists('src/api') || exists('routes'),
    isServer: exists('server.js') || exists('src/server.ts') || exists('src/index.ts'),
    envFiles: [],
    outdatedDeps: [],
    largeFiles: [],
    circularDeps: [],
    hasJsFiles: true,
    hasAPIDocs: exists('docs/api') || exists('openapi.json') || exists('swagger.json'),
    hasInputValidation: false,
    hasModuleBoundaries: false,
    tryCatchRatio: null,
    testCoverage: null,
    sourceFileCount: 0,
  };
}

module.exports = { healthScore, maturityLevel, generateReport, DIMENSIONS, MATURITY_LEVELS };
